### PR TITLE
YU-GI-OH! React Capstone

### PR DESCRIPTION
**Pull request by mohametalmeari**
- [x] Select API
- [x] Build files structure for React app
- [x] Prepare routes and navigation in the app
- [x] Display a list of items and filter them
- [x] Create tests for the application
- [x] Style components
- [x] Deploy the project
- [x] Record a video
- [x] Create README and PR description

### CODE REVIEW

**Review by AlphaNtihinduka — CHANGES_REQUESTED** [review]
## Hi @mohametalmeari     🙋‍♂️
Good job working on your react capstone. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement few on the project but you are almost there!!! 🚶: 

TO HIGHLIGHT:
- Proper use of dispatch method ✔️ 
- Correct usage of `react-router-dom` to serve each page without reloading.

- Well-structured files ✅

# STATUS: Required Changes :recycle: 

close

# STATUS: Required Changes :recycle: 
- [ ] As the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#project-documentation) suggest, you should  record a video presenting the features of the project you built. The video should have a maximum length of 5 minutes ☺️.
_- Kindly consider the inline review comments ☺️._

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

**Comment by mohametalmeari** [comment]
Thanks a lot for the review and the kind feedback, I will complete my project and resubmit

**Review by ichala — APPROVED** [review]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mohametalmeari** [comment]
Thank you for the review

**Pull request merged**
